return {
	kind_icons = {
		Text = "",
		Method = "󰆧",
		Function = "󰊕",
		Constructor = "",
		Field = "󰜢",
		Variable = "󰀫",
		Property = "",
		Class = "󰌗",
		Interface = "",
		Struct = "󰌗",
		Module = "",
		Unit = "󰑭",
		Value = "󰎠",
		Enum = "",
		EnumMember = "",
		Keyword = "󰌋",
		Constant = "󰏿",
		Snippet = "",
		Color = "󰏘",
		File = "󰈙",
		Reference = "󰈇",
		Folder = "󰉋",
		Event = "",
		Operator = "󰆕",
		TypeParameter = "󰊄",
	},
	vim.api.nvim_set_hl(0, "BlinkCmpKindCodeium", { fg = "#8CC55B" }),
	vim.api.nvim_set_hl(0, "BlinkCmpKindSnippet", { fg = "#FF9D00" }),
}
